language: cpp
compiler:
  - g++
os:
  - linux
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - cmake-data
      - cmake
      - build-essential
      - libgtest-dev
script:
  - cmake . && make
  - ls bin
  - bin/main-test

before_install:
  - cp .netrc ~
  - chmod 600 .netrc