language: cpp

compiler:
  - clang++

os:
  - linux


addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - cmake-data
      - cmake
      - clang-3.8

script:
  - cmake && make
  - ./main-test



before_install:
  - cp .netrc ~
  - chmod 600 .netrc